// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggxjooktmatzdryrkerr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneGpvb2t0bWF0emRyeXJrZXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTA4MjIsImV4cCI6MjA2OTk4NjgyMn0.K8Fk_aOVmx3bH69ogfBwXmTTI-Awo1xz2amSYaJV4b4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});